//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storehouse.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string BrandName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> StorageId { get; set; }
    
        public virtual Provider Provider { get; set; }
        public virtual Storage Storage { get; set; }
        public virtual TypeProduct TypeProduct { get; set; }
    }
}
